In [2]:
import pandas as pd

codebook : https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf

In [3]:
brfss = pd.read_csv('2015.csv')
brfss

_STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE  \
0          1.0     1.0  b'01292015'  b'01'  b'29'  b'2015'    1200.0   
1          1.0     1.0  b'01202015'  b'01'  b'20'  b'2015'    1100.0   
2          1.0     1.0  b'02012015'  b'02'  b'01'  b'2015'    1200.0   
3          1.0     1.0  b'01142015'  b'01'  b'14'  b'2015'    1100.0   
4          1.0     1.0  b'01142015'  b'01'  b'14'  b'2015'    1100.0   
...        ...     ...          ...    ...    ...      ...       ...   
441451    72.0    11.0  b'12162015'  b'12'  b'16'  b'2015'    1100.0   
441452    72.0    11.0  b'12142015'  b'12'  b'14'  b'2015'    1100.0   
441453    72.0    11.0  b'12232015'  b'12'  b'23'  b'2015'    1200.0   
441454    72.0    11.0  b'12152015'  b'12'  b'15'  b'2015'    1100.0   
441455    72.0    11.0  b'12152015'  b'12'  b'15'  b'2015'    1100.0   

               SEQNO          _PSU  CTELENUM  ...  _PAREC1  _PASTAE1  \
0       2.015000e+09  2.015000e+09       1.0  ...      4.0       2.0   
1       2.015000e+09  2.015000e+09       1.0  ...      2.0       2.0   
2       2.015000e+09  2.015000e+09       1.0  ...      9.0       9.0   
3       2.015000e+09  2.015000e+09       1.0  ...      4.0       2.0   
4       2.015000e+09  2.015000e+09       1.0  ...      4.0       2.0   
...              ...           ...       ...  ...      ...       ...   
441451  2.015005e+09  2.015005e+09       NaN  ...      4.0       2.0   
441452  2.015005e+09  2.015005e+09       NaN  ...      2.0       2.0   
441453  2.015005e+09  2.015005e+09       NaN  ...      9.0       9.0   
441454  2.015005e+09  2.015005e+09       NaN  ...      4.0       2.0   
441455  2.015005e+09  2.015005e+09       NaN  ...      4.0       2.0   

        _LMTACT1  _LMTWRK1  _LMTSCL1  _RFSEAT2  _RFSEAT3  _FLSHOT6  _PNEUMO2  \
0            1.0       1.0       1.0       1.0       1.0       NaN       NaN   
1            3.0       3.0       4.0       2.0       2.0       NaN       NaN   
2            9.0       9.0       9.0       9.0       9.0       9.0       9.0   
3            1.0       1.0       1.0       1.0       1.0       NaN       NaN   
4            1.0       1.0       1.0       1.0       1.0       NaN       NaN   
...          ...       ...       ...       ...       ...       ...       ...   
441451       2.0       2.0       3.0       1.0       1.0       2.0       2.0   
441452       3.0       3.0       4.0       1.0       1.0       NaN       NaN   
441453       3.0       3.0       4.0       9.0       9.0       9.0       9.0   
441454       3.0       3.0       4.0       1.0       1.0       NaN       NaN   
441455       3.0       3.0       4.0       1.0       1.0       NaN       NaN   

        _AIDTST3  
0            1.0  
1            2.0  
2            NaN  
3            9.0  
4            1.0  
...          ...  
441451       2.0  
441452       1.0  
441453       NaN  
441454       2.0  
441455       1.0  

[441456 rows x 330 columns]

In [20]:
brfss['MENTHLTH']

0         18.0
1          0.0
2          0.0
3         30.0
4          0.0
          ... 
441451     0.0
441452     0.0
441453    20.0
441454     0.0
441455     0.0
Name: MENTHLTH, Length: 441456, dtype: object

In [5]:
# replacing 88 with 0 because 88 means none (codebook)
brfss.loc[(brfss.MENTHLTH == 88),'MENTHLTH']=0

In [7]:
# replacing 77 and 99 with NA (codebook)
brfss.loc[(brfss.MENTHLTH == 77),'MENTHLTH']= pd.NA
brfss.loc[(brfss.MENTHLTH == 99),'MENTHLTH']= pd.NA

In [ ]:
brfss['MENTHLTH']

In [13]:
# finding 2 standard deviations above the mean
brfss['MENTHLTH'].mean() + (2*(brfss['MENTHLTH'].std()))

18.54709472332798

In [35]:
# create new column with the people above 2 sd above the mean calssified as poor mental health,
# and all others classified as not
brfss['POOR_MENTHLTH'] = brfss['MENTHLTH']

In [39]:
brfss.loc[(brfss.POOR_MENTHLTH >= 18.0),'POOR_MENTHLTH']=1

In [37]:
brfss.loc[(brfss.POOR_MENTHLTH <= 18.5),'POOR_MENTHLTH']=0

In [41]:
brfss['POOR_MENTHLTH'].sum()

32051

In [42]:
len(brfss['POOR_MENTHLTH'])

441456

In [43]:
32051/441456

0.07260293211554493

There are 32,051 people with mental health poorer in the last 30 days than 2 standard deviations above the mean. There are 441,456 total observations. This is about 7% of the observations.  